In [13]:
from sklearn.datasets import load_iris
import pandas as pd
import numpy as np 
from matplotlib import pyplot as plt
from sklearn import tree as treeClassifier
from sklearn.ensemble import RandomForestClassifier as forest
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, accuracy_score
from sklearn.neural_network import MLPClassifier
from sklearn.linear_model import LogisticRegression
import time

In [2]:
datos = load_iris()
datos.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [3]:
datos["target_names"]

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [4]:
dataset = pd.DataFrame(data = datos["data"], columns =  datos["feature_names"])
dataset["especie"] = datos["target"]
dataset

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

     especie  
0          0  
1          0  
2          0  
3          0  
4          0  
..       ...  
145        2  
146        2  
147        2  
148        2  
149        2  

[150 rows x 5 columns]

## Queremos obtener un conjunto de reglas de árbol de decisión para clasificar la especie de flor con las 4 medidas que tenemos

### Separación de datos

In [5]:
x_train, x_test, y_train, y_test = train_test_split(dataset.drop('especie', axis = 1), dataset['especie'], test_size = 0.3)

In [6]:
# arbol de decision
start_arbol = time.time()
arbol = treeClassifier.DecisionTreeClassifier()
arbol.fit(x_train, y_train)
# predicción para los datos de prueba
pred_arbol = arbol.predict(x_test)
t_arbol = time.time() - start_arbol
ac_arbol = accuracy_score(y_pred=pred_arbol, y_true=y_test)
print("Accuracy score: {}".format(accuracy_score(y_pred=pred_arbol, y_true=y_test)))
print("Matriz de confusión:\n{}".format(confusion_matrix(y_pred=pred_arbol, y_true=y_test)))

Accuracy score: 0.9333333333333333
Matriz de confusión:
[[15  0  0]
 [ 0 14  2]
 [ 0  1 13]]


In [8]:
# bosque aleatorio
start_bosque = time.time()
bosque = forest(800)
bosque.fit(x_train, y_train)
# predicción para los datos de prueba
pred_bosque = bosque.predict(x_test)
t_bosque = time.time() - start_bosque
ac_bosque = accuracy_score(y_pred=pred_bosque, y_true=y_test)
print("Accuracy_score: {}".format(accuracy_score(y_pred=pred_bosque, y_true=y_test)))
print("Matriz de confusión:\n{}".format(confusion_matrix(y_pred=pred_bosque, y_true=y_test)))

Accuracy_score: 0.9333333333333333
Matriz de confusión:
[[15  0  0]
 [ 0 15  1]
 [ 0  2 12]]


In [11]:
start_red = time.time()
redNeuronal = MLPClassifier(hidden_layer_sizes=(10,4,3),
                            max_iter=10000,
                            activation ='logistic',
                            tol= 1e-7)

redNeuronal.fit(x_train, y_train)
pred_rn = redNeuronal.predict(x_test)
t_red = time.time() - start_red
ac_rn = accuracy_score(y_pred=pred_rn, y_true=y_test)
print("Accuracy_score: {}".format(accuracy_score(y_pred=pred_rn, y_true=y_test)))
print("Matriz de confusión:\n{}".format(confusion_matrix(y_pred=pred_rn, y_true=y_test)))

Accuracy_score: 0.9777777777777777
Matriz de confusión:
[[15  0  0]
 [ 0 15  1]
 [ 0  0 14]]


c:\Users\alonso.sandoval\AppData\Local\anaconda3\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (10000) reached and the optimization hasn't converged yet.
  warnings.warn(


In [14]:
start_logi = time.time()
logi = LogisticRegression()
logi.fit(x_train, y_train)
pred_logi = logi.predict(x_test)
t_logi = time.time() - start_logi
ac_logi = accuracy_score(y_pred=pred_logi, y_true=y_test)
print("Accuracy_score: {}".format(accuracy_score(y_pred=pred_logi, y_true=y_test)))
print("Matriz de confusión:\n{}".format(confusion_matrix(y_pred=pred_logi, y_true=y_test)))

Accuracy_score: 0.9555555555555556
Matriz de confusión:
[[15  0  0]
 [ 0 15  1]
 [ 0  1 13]]


In [16]:
resultados = pd.DataFrame({'modelo': ['regresión logística', 'arbol', 'bosque', 'red neuronal'],
'accuracy': [ac_logi, ac_arbol, ac_bosque, ac_rn],
'tiempo': [t_logi, t_arbol, t_bosque, t_red]})
resultados

modelo  accuracy     tiempo
0  regresión logística  0.955556   0.033224
1                arbol  0.933333   0.008096
2               bosque  0.933333   2.464111
3         red neuronal  0.977778  10.364004